mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  mvc:
    converters:
      preferred-json-mapper: gson
  datasource:
    url: jdbc:mysql://roundhouse.proxy.rlwy.net:49047/calgary_bus_infomation
    username: root
    password: EDHhe54cbgh-41B36e3c6E62G2afc4Ea
    driver-class-name: com.mysql.cj.jdbc.Driver